### ISSUE TITLE
Test code or dataset

### ISSUE THREAD

**Issue by dklee98** [jingGM/DTG#1]
Hi, I am trying to test your awesome method, but there is no test code or predefined model.

The opened code contains train.py, but there is no dataset.
the training process requires "data_root" that isn't in the directory (/home/jing/Documents/gn/database/datasets/regular_data/data.pkl)

Could you have any plan to open your predefined model or dataset??

thank you

**Comment by jingGM** [comment]
We are planning to publish a dataset in our next work for general outdoor navigation tasks with small mobile robots, and it will include the dataset we used for DTG. The real-world implementation is currently built in our mapless navigation pipeline, but we are using this pipeline for other projects. After these projects, we will publish pre-trained models and the pipeline.

**Comment by Lin-zhiyuan** [comment]
Hi, your method is awesome, I'm trying to test your method, but there is no train data. Now, I want to use my own data collected before, so can you explain the data-structure of your dataset? And the target is the GPS tranformed to UTM?

**Comment by jingGM** [comment]
Our dataset is now available at this link, https://cs.gmu.edu/~xiao/Research/GND/, and it is fully open-sourced. In our DTG approach, we  utilized only the white regions of the maps to represent traversable areas.

To further encourage the global robotics research community to develop their own campus datasets, we have also released our full data processing pipeline, starting from raw rosbags, at this GitHub repository: https://github.com/jingGM/GND.git. You are very welcome to contribute to the dataset with your campus data.

**Comment by dklee98** [comment]
Thank you for your kindness and grateful answer.
I agree that your open data encourages the robotics community, including me.
