### ISSUE TITLE
question:target coordinate and position

### ISSUE THREAD

**Issue by heyshouzi** [jingGM/DTG#4]
good work!

There are two question in your paper,could you please help me to answer them ?

First,What coordinate system is the input target in? It it in GPS coordinates or odom coordinates?

Secondly, What is your method of determining wheter the robot has reached the specified target?

hoping your answer.

**Comment by jingGM** [comment]
1. We use the robot's coordinate for input target location, as well as generated trajectories. GPS position is converted into robot's frame as input.
2. The termination of robot's navigation depends on how you do implementation. In the video of our experiment, we use GPS distance to stop the robot.

**Comment by heyshouzi** [comment]
Thinks your answer.
